version: '2.1'

networks:
  oninet:
    driver: bridge

services:
  swag:
    image: ghcr.io/linuxserver/swag
    environment:
      - TZ=Europe/London
      - URL=archives.aragonoutlook.org
      - CERTPROVIDER=zerossl
      - EMAIL=w0pw6n914@mozmail.com
    volumes:
      - "./reverse-proxy/default.conf:/config/nginx/site-confs/default:ro"
    depends_on:
      - web
    ports:
      - 443:443
      - 80:80 #optional
    networks:
      - oninet
  rdbms:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=openoni
      - MYSQL_USER=openoni
      - MYSQL_PASSWORD=openoni
    volumes:
      - ./conf/mysql/:/etc/mysql/conf.d:Z
      - data-mariadb:/var/lib/mysql
    networks:
      - oninet
  solr:
    image: solr:8.3-slim
    volumes:
      - data-solr:/var/solr
    command:
      - solr-precreate
      - openoni
    networks:
      - oninet
  rais:
    image: uolibraries/rais:4
    environment:
      - RAIS_IIIFWEBPATH=/images/iiif
      - RAIS_IIIFBASEURL=${ONI_BASE_URL:-http://localhost}
      - RAIS_TILECACHELEN=250
      - RAIS_TILEPATH=/opt/openoni/data/batches
    volumes:
      # Image files must be available at RAIS_TILEPATH
      - ./data/batches:/opt/openoni/data/batches:z
    networks:
      - oninet
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/opt/openoni:z
      - "/home/ec2-user/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem"
      - "/home/ec2-user/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key"
    # ports:
      # - ${HTTPPORT:-80}:80
      # - 443:443
    depends_on:
      - rdbms
    links:
      - rdbms
      - solr
      - rais
    environment:
      - APACHE_LOG_LEVEL=${APACHE_LOG_LEVEL:-warn}
      - ONI_BASE_URL
      - ONI_DB_HOST
      - ONI_DB_PORT
      - ONI_DB_NAME
      - ONI_DB_USER
      - ONI_DB_PASSWORD
      - ONI_DEBUG
      - ONI_HSTS_SECONDS
      - ONI_IIIF_URL
      - ONI_LOG_SQL
      - ONI_LOG_TO_FILE
      - ONI_SECRET_KEY
      - ONI_SOLR_URL
    networks:
      - oninet

volumes:
  data-mariadb: {}
  data-solr: {}
